git:
  submodules: false

sudo: required

matrix:
  include:
    - os: linux
      env: "daemonIntegration=true"
      addons: 
        apt:
          sources:
            - sourceline: 'deb https://bluzelle.jfrog.io/bluzelle/debian-local all stable'

    - os: osx
      env: "emulatorIntegration=true"


language: node_js

node_js:
  - "node" # Use latest NodeJS

before_install:
  - ./travis_install.sh