git:
  submodules: false

sudo: required

matrix:
  include:
    - os: linux
      env: "daemonIntegration=true"
      addons: 
        apt:
          sources:
            - sourceline: 'deb https://bluzelle.jfrog.io/bluzelle/debian-local all stable'
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty main'
          packages:
            - g++-7
            - pkg-config
            - protobuf-compiler
            - libprotobuf-dev
    - os: osx
      env: "emulatorIntegration=true"


language: node_js

node_js:
  - "node" # Use latest NodeJS

before_install:
  - ./travis_install.sh
