git:
  submodules: false

sudo: required

env:
  global:
    - PROJECT_VERSION_MAJOR="0"
    - PROJECT_VERSION_MINOR="2"
    - PROJECT_VERSION_PATCH="${TRAVIS_BUILD_NUMBER}"
    - PROJECT_VERSION="${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}"

matrix:
  include:
    - os: linux
      env: "daemonIntegration=true"
      addons: 
        apt:
          sources:
            - sourceline: 'deb https://bluzelle.jfrog.io/bluzelle/debian-local all unstable'
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty main'
    - os: osx
      env: "emulatorIntegration=true"


language: node_js

node_js:
  - "node" # Use latest NodeJS

before_install:
  - ./travis_install.sh


after_success:
- if [ "$TRAVIS_BRANCH" = "master" ]; then
    npm version "$PROJECT_VERSION"
    npm publish;
  fi
