/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.peer', null, global);
goog.exportSymbol('proto.state_msg', null, global);
goog.exportSymbol('proto.state_msg.RaftState', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.peer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.peer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.peer.displayName = 'proto.peer';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.peer.prototype.toObject = function(opt_includeInstance) {
  return proto.peer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.peer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.peer.toObject = function(includeInstance, msg) {
  var f, obj = {
    host: jspb.Message.getFieldWithDefault(msg, 1, ""),
    port: jspb.Message.getFieldWithDefault(msg, 2, 0),
    httpPort: jspb.Message.getFieldWithDefault(msg, 3, 0),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    uuid: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.peer}
 */
proto.peer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.peer;
  return proto.peer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.peer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.peer}
 */
proto.peer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPort(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHttpPort(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.peer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.peer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.peer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.peer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPort();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getHttpPort();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string host = 1;
 * @return {string}
 */
proto.peer.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.peer.prototype.setHost = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 port = 2;
 * @return {number}
 */
proto.peer.prototype.getPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.peer.prototype.setPort = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 http_port = 3;
 * @return {number}
 */
proto.peer.prototype.getHttpPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.peer.prototype.setHttpPort = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.peer.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.peer.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string uuid = 5;
 * @return {string}
 */
proto.peer.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.peer.prototype.setUuid = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.state_msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.state_msg.repeatedFields_, null);
};
goog.inherits(proto.state_msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.state_msg.displayName = 'proto.state_msg';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.state_msg.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.state_msg.prototype.toObject = function(opt_includeInstance) {
  return proto.state_msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.state_msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.state_msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    raftstate: jspb.Message.getFieldWithDefault(msg, 2, 0),
    leaderuuid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    numdbs: jspb.Message.getFieldWithDefault(msg, 4, 0),
    totaldbsize: jspb.Message.getFieldWithDefault(msg, 5, 0),
    totalkvp: jspb.Message.getFieldWithDefault(msg, 6, 0),
    crudcommits: jspb.Message.getFieldWithDefault(msg, 7, 0),
    peersList: jspb.Message.toObjectList(msg.getPeersList(),
    proto.peer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.state_msg}
 */
proto.state_msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.state_msg;
  return proto.state_msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.state_msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.state_msg}
 */
proto.state_msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {!proto.state_msg.RaftState} */ (reader.readEnum());
      msg.setRaftstate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLeaderuuid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumdbs(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotaldbsize(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTotalkvp(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCrudcommits(value);
      break;
    case 8:
      var value = new proto.peer;
      reader.readMessage(value,proto.peer.deserializeBinaryFromReader);
      msg.addPeers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.state_msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.state_msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.state_msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.state_msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRaftstate();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getLeaderuuid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNumdbs();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getTotaldbsize();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getTotalkvp();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getCrudcommits();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getPeersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.peer.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.state_msg.RaftState = {
  ELECTION: 0,
  NONELECTION: 1
};

/**
 * optional RaftState raftState = 2;
 * @return {!proto.state_msg.RaftState}
 */
proto.state_msg.prototype.getRaftstate = function() {
  return /** @type {!proto.state_msg.RaftState} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.state_msg.RaftState} value */
proto.state_msg.prototype.setRaftstate = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string leaderUuid = 3;
 * @return {string}
 */
proto.state_msg.prototype.getLeaderuuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.state_msg.prototype.setLeaderuuid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 numDbs = 4;
 * @return {number}
 */
proto.state_msg.prototype.getNumdbs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.state_msg.prototype.setNumdbs = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 totalDbSize = 5;
 * @return {number}
 */
proto.state_msg.prototype.getTotaldbsize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.state_msg.prototype.setTotaldbsize = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 totalKVP = 6;
 * @return {number}
 */
proto.state_msg.prototype.getTotalkvp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.state_msg.prototype.setTotalkvp = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 crudCommits = 7;
 * @return {number}
 */
proto.state_msg.prototype.getCrudcommits = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.state_msg.prototype.setCrudcommits = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * repeated peer peers = 8;
 * @return {!Array.<!proto.peer>}
 */
proto.state_msg.prototype.getPeersList = function() {
  return /** @type{!Array.<!proto.peer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.peer, 8));
};


/** @param {!Array.<!proto.peer>} value */
proto.state_msg.prototype.setPeersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.peer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.peer}
 */
proto.state_msg.prototype.addPeers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.peer, opt_index);
};


proto.state_msg.prototype.clearPeersList = function() {
  this.setPeersList([]);
};


goog.object.extend(exports, proto);
